services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  counter:
    image: nadbelyh/counter:latest
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  library:
    image: nadbelyh/books:latest
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - HOST_URL=counter
    depends_on:
      - counter
